[package]
name = "vector-racing-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
rand = "0.8.5"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3